apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ysb-llm-server
  name: ysb-llm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ysb-llm-server
  template:
    metadata:
      labels:
        app: ysb-llm-server
    spec:
      containers:
      - args:
        - |
          echo "Running GGUF Server By YSB"
          /app/llama-server --model /model2/llava-models/llava-phi-3-mini-f16.gguf --mmproj /models/llava-models/llava-phi-3-mini-mmproj-f16.gguf  --port 8001 --host 0.0.0.0  -n 40
        command:
        - /bin/sh
        - -c
        image: ghcr.io/yogeshbendre/yllamacpp:full
        imagePullPolicy: IfNotPresent
        name: inference
        resources:
          limits:
            cpu: "4"
            memory: 12Gi
          requests:
            cpu: 500m
            memory: 4Gi
        volumeMounts:
        - mountPath: /models
          name: model-volume
      volumes:
      - image:
          pullPolicy: IfNotPresent
          reference: ghcr.io/yogeshbendre/ysb-llava-mini:1.0
        name: model-volume
